permalink: /:year/:month/:day/:title.html
paginate: 10
# markdown: rdiscount
markdown: kramdown

# 作者信息
author: 
  name: 李乾坤
  email: qiankun.li@qq.com
  link: 
  weibo: 
  github: http://qiankunli.github.io

# 站点信息
title: 苍狗白云 
description: 苍狗白云
url: http://lianglu1024.github.io
rss_url: 



# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Docker
  - Java

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
plugins:
- jekyll-paginate
